language: go
os: linux
dist: bionic

go:
  - "stable"

notifications:
  email:
    recipients:
      - graygolem@gmail.com
    on_success: always
    on_failure: always

install: skip

script:
  - go test -v ./...
  - go build -o stush -race stush.go

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: "stush"
  cleanup: false
  on:
    tags: true
